# Python basics week 3 (last week of half half recap)
today: numpy, arrays, slicing, pywhatkit, maybe pythonic code


In [1]:
! python -m pip install numpy
#command to install a library


[notice] A new release of pip is available: 24.0 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [ ]:
import numpy
import numpy as np
from numpy import arange

## Creating arrays
array of elements has to be of the same datatype

In [ ]:
import numpy as np

list = [1, 5, 8, 10, 3]
print(list)

array = np.array(list)
print(array)

print(list * 2) #list is seen as a whole, it will duplicate the list and paste itself behind the first occurence.
print(array * 2) #treats every element separately to multiply

list.append(2)
#array.append(2)
#array.add(2) --> none of these 2 work, because arrays have a fixed size!

[1, 5, 8, 10, 3]
[ 1  5  8 10  3]
[1, 5, 8, 10, 3, 1, 5, 8, 10, 3]
[ 2 10 16 20  6]
[205   5   8  10   3]


In [ ]:
import numpy as np

#1D arrays
print(np.arange(10)) #--> fill an array with x numbers from 0 till x
print(np.zeros(10)) #fill an array with x 0's
print(np.ones(10)) 
#print(np.twos(10)) --> does not work, only ones and zeros

print(np.full(10, 5)) #fill array with certain length with specific number

print(np.random.randint(-5, 6, 10)) #--> remove the last digit and get only 1 number
print(np.random.random(10)) #x amount of random floats between 0 and 1.

[0 1 2 3 4 5 6 7 8 9]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[5 5 5 5 5 5 5 5 5 5]
[-4  2  2  0 -4 -2  0 -1  1  3]
[0.13420099 0.34412234 0.46075954 0.83131012 0.77736226 0.75964158
 0.98134874 0.66371048 0.09311202 0.16862574]


## Reshaping & converting an array

In [44]:
import numpy as np
array = np.random.randint(-5, 6, 10)

print(array)
print(len(array)) #works but only in 1D
print(array.shape)
print(array.ndim)

#checking datatype
print(f"array is of datatype: {array.dtype}")

#conversions between types of arrays
arrayFloater = array.astype(float) #str int float ...
print(arrayFloater)

arrayString = array.astype("S")
print(arrayString)

# i - integer / b - boolean / f - float / M - datetime / S - string / but wording also works (float, str, int, ...)


#2D array
array2D = np.reshape(array, (2,5)) #first number = rows, second number = columns
print(array2D)

array2D = np.reshape(array, (5,2))
print(array2D)

#array2D = np.reshape(array, (3,3))
#array2D = np.reshape(array, (4,3))
#print(array2D)

#has to perfectly fit!

[ 5 -2  2  3 -5  1  2  2 -4  0]
10
(10,)
1
array is of datatype: int32
[ 5. -2.  2.  3. -5.  1.  2.  2. -4.  0.]
[b'5' b'-2' b'2' b'3' b'-5' b'1' b'2' b'2' b'-4' b'0']
[[ 5 -2  2  3 -5]
 [ 1  2  2 -4  0]]
[[ 5 -2]
 [ 2  3]
 [-5  1]
 [ 2  2]
 [-4  0]]


## Slicing arrays

[start : end : step]
- start: number (index), included
- end: number (index), NOT included
- step: the size of a jump between values

In [ ]:
import numpy as np

array = np.array([6, 8, 2, 9, 0, 1, 3, 5, 7, 4])
print(array)

#I want the first 4 numbers of the array
print(array[0:4:1]) #[6 8 2 9]
print(array[:4:1])
print(array[:4:])

#I want the 8 2 9 0
print(array[1:5:])
print(array[1:4:2])

print(array[::])
#reverse
print(array[::-1])

#slice the last 4, but don't use the positive index
print(array[-4::])

print(array[-1:0:-1])
print(array[0:10:-1]) #prints nothing

[6 8 2 9 0 1 3 5 7 4]
[6 8 2 9]
[6 8 2 9]
[6 8 2 9]
[8 2 9 0]
[8 9]
[6 8 2 9 0 1 3 5 7 4]
[4 7 5 3 1 0 9 2 8 6]
[3 5 7 4]
[4 7 5 3 1 0 9 2 8]
[]


### Exercise on slicing
we want to generate an array of the temperature measurements EVERY hour throughout a day. (24 measurements)
generate random temps: between 0 and 25 (use random ints)
--> use slicing to isolate periods and analyse them
- earlyBirdFeedsTheWorm: all temps first 6 hours of the day (includes the temp at 00:00 --> 06:00)
- everyoneAwakeBEFORENOON: 09:00 - 13:00 (again the temps here)
- siesta: 14:00 - 16:00
- lateNightOwls: because they live in a different time, reverse the slice (LAST 4 MEASUREMENTS)
- trending: every 5 hours, startin at 00:00, 05:00, 10:00...

In [81]:
import numpy as np
import random

#temps = [random.randint(0, 26) for x in range(24)]
#measurements = np.array(temps)

measurements = np.random.randint(0, 26, 24)
print(measurements)

earlyBirdFeedsTheWorm = measurements[:6:]
print(earlyBirdFeedsTheWorm)

everyoneAwakeBeforeNOON = measurements[9:13:]
print(everyoneAwakeBeforeNOON)

siesta = measurements[14:17:]
print(siesta)

lateNightOwls = measurements[-1:-5:-1]
print("LAST 4", lateNightOwls)
lateNightOwls = measurements[:-4]
print(lateNightOwls)


trending = measurements[::5]
print(trending)

[17 23 22  4  7  7 18 18  0 16 15 19 21 15 23 21  7 16 22  5 11 20 14 18]
[17 23 22  4  7  7]
[16 15 19 21]
[23 21  7]
LAST 4 [18 14 20 11]
[17 23 22  4  7  7 18 18  0 16 15 19 21 15 23 21  7 16 22  5]
[17  7 15 21 11]


## Working with arrays

In [18]:
import numpy as np

a = np.arange(0,10)
b = np.arange(9,-1,-1)
print(a, b)

print(a + b)
print(a - b)
print(a * b)

print(np.where(a % 2 == 0, a + 5, a))
print(np.where(a % 2 == 0))

array = np.where(a % 2 == 0)
print(array[0]) #the regular np.where with only a condition and no True or False, returns a tuple with the indexes
#of the values where the condition is met.

print(np.where(b>5))
meetingCondition = np.where(b>5)[0]
print(meetingCondition)

b = np.reshape(b, (2,5))
print(b)
print()

print(b.sum(axis = 0)) #sum of all columns each counted up together
print(b.sum(axis = 1)) #sum of each row
print(b.cumsum(axis = 1))

print()
print(a.sum())
print(a.min())
print(a.max())

print(np.sqrt(a)) #square root of each number in a
print(np.sqrt(a.max()))

[0 1 2 3 4 5 6 7 8 9] [9 8 7 6 5 4 3 2 1 0]
[9 9 9 9 9 9 9 9 9 9]
[-9 -7 -5 -3 -1  1  3  5  7  9]
[ 0  8 14 18 20 20 18 14  8  0]
[ 5  1  7  3  9  5 11  7 13  9]
(array([0, 2, 4, 6, 8]),)
[0 2 4 6 8]
(array([0, 1, 2, 3]),)
[0 1 2 3]
[[9 8 7 6 5]
 [4 3 2 1 0]]

[13 11  9  7  5]
[35 10]
[[ 9 17 24 30 35]
 [ 4  7  9 10 10]]

45
0
9
[0.         1.         1.41421356 1.73205081 2.         2.23606798
 2.44948974 2.64575131 2.82842712 3.        ]
3.0


In [19]:
import this

The Zen of Python, by Tim Peters

Beautiful is better than ugly.
Explicit is better than implicit.
Simple is better than complex.
Complex is better than complicated.
Flat is better than nested.
Sparse is better than dense.
Readability counts.
Special cases aren't special enough to break the rules.
Although practicality beats purity.
Errors should never pass silently.
Unless explicitly silenced.
In the face of ambiguity, refuse the temptation to guess.
There should be one-- and preferably only one --obvious way to do it.
Although that way may not be obvious at first unless you're Dutch.
Now is better than never.
Although never is often better than *right* now.
If the implementation is hard to explain, it's a bad idea.
If the implementation is easy to explain, it may be a good idea.
Namespaces are one honking great idea -- let's do more of those!


In [ ]:
! python -m pip install pywhatkit

In [ ]:
import pywhatkit

pywhatkit.sendwhatmsg("NUMBER", "Hey Anthony, this is another test, kind regards, YOUR STALKER", 
16, 38, 15, True, 2)

In 57 Seconds WhatsApp will open and after 15 Seconds Message will be Delivered!
