# Python basics - week 3 (last)
to do: working with packages (numpy, pywhatcat)
and maybe some Pythonic code

In [ ]:
! python -m pip install numpy


[notice] A new release of pip is available: 24.0 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip


## Import numpy

In [ ]:
import numpy
import numpy as np
from numpy import arange

### Creating arrays
array elements that must have the same type

In [ ]:
import numpy as np
list = [1, 5, 8, 10, 3]
print(list)

array = np.array(list)
print(array)

print(list*2)
print(array*2)
#list --> seen as whole and is completely doubles in size. (everything is multiplied at once) [1, 5, 8, 10, 3, 1, 5, 8, 10, 3]
#array --> will store each element and multiply each element

list.append(2)
#array.append(2) cannot append like this.
#array.add(8) or like this. 
print(list)
print(array) #fixed size so cannot increase or decrease

#1D arrays
print(np.arange(10)) #evenly spaced intervals with given key, without upperbound --> key is the end index.
print(np.zeros(10)) #filled with x amounts of 0's, but all are floats
print(np.ones(10)) #LIMITED EDITION: ONLY ZEROS AND ONES

print(np.full(10,5)) #fill an array of x length, with number y --> full(x,y)
print(np.random.randint(-5,6,10)) #lower boundary included, upper NOT, amount of numbers
print(np.random.random(10)) #x amount of random floats

[1, 5, 8, 10, 3]
[ 1  5  8 10  3]
[1, 5, 8, 10, 3, 1, 5, 8, 10, 3]
[ 2 10 16 20  6]
[1, 5, 8, 10, 3, 2]
[ 1  5  8 10  3]
[0 1 2 3 4 5 6 7 8 9]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[5 5 5 5 5 5 5 5 5 5]
[-1 -1 -4 -4  4  0  3 -4  1  4]
[0.87338308 0.68408864 0.50343546 0.2715732  0.99470126 0.54939004
 0.41094713 0.33672239 0.3579606  0.32026773]


## Reshaping & converting an array

In [37]:
import numpy as np

#change the array again to start off with
array = np.random.randint(-10, 11, 10)
print(array)
print(array.shape) #amount of elements in array --> dimensions
print(array.ndim) #number of dimensions

print("array is of type:", array.dtype)
arrayFloater = array.astype("f")
print(arrayFloater)

# i - integer / b - boolean / f - float / S - string / wording also works: str int bool / M - datetime

arrayString = array.astype(str)
print(arrayString)

#reshaping from 1D to 2D
array2D = np.reshape(array, (2,5))
print(array2D)

array2D = np.reshape(array, (5,2))
print(array2D)
print(array2D.shape)
print(array2D.ndim)
print(len(array2D))

#careful, because it does need to be a perfect fit.
#array2D = np.reshape(array, (3,3))
#array2D = np.reshape(array, (3,4))
#print(array2D) --> reshaping to a smaller size that doesn't fit everything or a bigger one than the max, IMPOSSIBLE


[ 7  2  5 -4 -7  4 -2  6 -2  8]
(10,)
1
array is of type: int32
[ 7.  2.  5. -4. -7.  4. -2.  6. -2.  8.]
['7' '2' '5' '-4' '-7' '4' '-2' '6' '-2' '8']
[[ 7  2  5 -4 -7]
 [ 4 -2  6 -2  8]]
[[ 7  2]
 [ 5 -4]
 [-7  4]
 [-2  6]
 [-2  8]]
(5, 2)
2
5


## Slicing arrays
[ start : end : step ]

- start: starting index
- end: end index (not included)
- step: step count of how big a jump we make from 1 to the other

In [53]:
import numpy as np

array = np.array([6, 8, 2, 9, 1, 3, 4, 7, 0, 5])
print(array)

print(array[1:5:1]) #[8 2 9 1]
print(array[1:5:]) #same result, 1 is the default STEP
print(array[1:5:2]) #[8 9]

print(array[0:5:2]) #[6 2 1]
print(array[:5:2]) #same, default start is 0

#print the whole thing with
print(array[0::1]) #default end is always the last element

#reverse an array
print(array[::-1])
print(array[10::-1])

print(array[::-2])

#going from 0 (second to last) up until 6 (start)
print(array[-2::-1])

#NOW what if I want to end at the 8 instead of the 6
print(array[-2:0:-1])

#some things to think about
print(array[0:10:-1])

[6 8 2 9 1 3 4 7 0 5]
[8 2 9 1]
[8 2 9 1]
[8 9]
[6 2 1]
[6 2 1]
[6 8 2 9 1 3 4 7 0 5]
[5 0 7 4 3 1 9 2 8 6]
[5 0 7 4 3 1 9 2 8 6]
[5 7 3 9 8]
[0 7 4 3 1 9 2 8 6]
[0 7 4 3 1 9 2 8]
[]


### An exercise on slicing
We are going to create a list of 24 temperature measurements, 1 for every part/hour of the day. You will isolate certain segments and analyse a trend with slicing.

--> make a list with measurements (24 integers) (between 5 and 25)
--> slicing part:
- morning: from 06:00 -> 10:00
- late evening: last 4 hours of the day (20:00 - 23:00)
- trend watching: every 3 hours starting at midnight --> 00:00, 03:00, 06:00, ...
- siesta: (12:00 - 16:00) --> because everyone is sleeping, REVERSE THIS!


In [63]:
import numpy, random

temps = [random.randint(5, 26) for x in range(24)]
ArrayTemps = np.array(temps)
print(ArrayTemps)


measurements = np.random.randint(5, 26, 24)
print(measurements)

#morning temps
morning = measurements[6:10:]
print(morning)

#late evening
last = measurements[20::]
last = measurements[-4::]
print(last)

#trend
trend = measurements[::3]
print(trend)

#siesta
siesta = measurements[16:11:-1]
print(siesta)

[ 9  5 11 22 10 25 24  8 23 23 21 10 25 24 22  6 19 15 22  6 12 14 12 10]
[ 6  5 16 12 12 16 24 14 20  9 17 13 21  7 23 16  7 16 20 18 14 20 11 13]
[24 14 20  9]
[14 20 11 13]
[ 6 12 24  9 21 16 20 20]
[ 7 16 23  7 21]


## Working with arrays

In [ ]:
import numpy as np

list1 = [1, 2, 3]
list2 = [4, 5, 6]


a = np.arange(0,10)
b = np.arange(9, -1, -1)
print(a,b)

#lists get merged
print(list1, list2)
print(list1 + list2)

#arrays add up the numbers
print(a + b)
print(a - b)
print(a * b)

print(np.where(a % 2 == 0, a + 1, a)) #check a condition, if true, first part after , --> if false, second part

arrayTEST = np.where(b>5)[0]
print(arrayTEST[0]) #// ADD [0] if you didn't add it on previous line! 
#navigate through tuple to be able to save the array gotten from the np.where 

print(np.where(b > 5)) #you get a return of indexes
print(np.where(b > 5, b, 0))

b = np.reshape(b, (2,5))
print(b)
print()

print(b.sum(axis=0)) #sum of all columns
print(b.sum(axis=1)) #sum of the rows
print(b.cumsum(axis=1)) #sum of all elements in row (slowly added up)

print(a.sum()) #45
print(a.min()) #0
print(a.max()) #9

print()
print(np.sqrt(a)) #square root of all numbers in a
print(np.sqrt(a.max())) #square root of highest value in a


[0 1 2 3 4 5 6 7 8 9] [9 8 7 6 5 4 3 2 1 0]
[1, 2, 3] [4, 5, 6]
[1, 2, 3, 4, 5, 6]
[9 9 9 9 9 9 9 9 9 9]
[-9 -7 -5 -3 -1  1  3  5  7  9]
[ 0  8 14 18 20 20 18 14  8  0]
[1 1 3 3 5 5 7 7 9 9]
0
(array([0, 1, 2, 3]),)
[9 8 7 6 0 0 0 0 0 0]
[[9 8 7 6 5]
 [4 3 2 1 0]]

[13 11  9  7  5]
[35 10]
[[ 9 17 24 30 35]
 [ 4  7  9 10 10]]
45
0
9

[0.         1.         1.41421356 1.73205081 2.         2.23606798
 2.44948974 2.64575131 2.82842712 3.        ]
3.0


In [84]:
import this

The Zen of Python, by Tim Peters

Beautiful is better than ugly.
Explicit is better than implicit.
Simple is better than complex.
Complex is better than complicated.
Flat is better than nested.
Sparse is better than dense.
Readability counts.
Special cases aren't special enough to break the rules.
Although practicality beats purity.
Errors should never pass silently.
Unless explicitly silenced.
In the face of ambiguity, refuse the temptation to guess.
There should be one-- and preferably only one --obvious way to do it.
Although that way may not be obvious at first unless you're Dutch.
Now is better than never.
Although never is often better than *right* now.
If the implementation is hard to explain, it's a bad idea.
If the implementation is easy to explain, it may be a good idea.
Namespaces are one honking great idea -- let's do more of those!


In [85]:
! python -m pip install pywhatkit

     ---------------------------------------- 0.0/61.2 kB ? eta -:--:--
     -------------------- ------------------- 30.7/61.2 kB 1.4 MB/s eta 0:00:01
     ---------------------------------------- 61.2/61.2 kB 1.1 MB/s eta 0:00:00
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
     ---------------------------------------- 0.0/171.2 kB ? eta -:--:--
     ------------------------------

  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.

[notice] A new release of pip is available: 24.0 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [87]:
import pywhatkit

#pywhatkit.sendwhatmsg(NUMBER, "Hey Anthony, everything allright?", 12, 30, 15, True, 2) 
#phonenr, message, hh, mm, sleeptime(15), True, closing after x

pywhatkit.playonyt("Jake Paul")

'https://www.youtube.com/watch?v=PgL5mq2zEzk\\\\u0026pp=ygUJSmFrZSBQYXVs'